/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as MissionVisionRouteImport } from './routes/mission-vision'
import { Route as ProgramsEnvironmentsRouteImport } from './routes/programs-environments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionRoute = MissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsEnvironmentsRoute = ProgramsEnvironmentsRouteImport.update({
  id: '/programs-environments',
  path: '/programs-environments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admissions': typeof AdmissionsRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/mission-vision': typeof MissionVisionRoute
  '/programs-environments': typeof ProgramsEnvironmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admissions': typeof AdmissionsRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/mission-vision': typeof MissionVisionRoute
  '/programs-environments': typeof ProgramsEnvironmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admissions': typeof AdmissionsRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/mission-vision': typeof MissionVisionRoute
  '/programs-environments': typeof ProgramsEnvironmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admissions'
    | '/blogs'
    | '/careers'
    | '/contact-us'
    | '/faqs'
    | '/mission-vision'
    | '/programs-environments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admissions'
    | '/blogs'
    | '/careers'
    | '/contact-us'
    | '/faqs'
    | '/mission-vision'
    | '/programs-environments'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admissions'
    | '/blogs'
    | '/careers'
    | '/contact-us'
    | '/faqs'
    | '/mission-vision'
    | '/programs-environments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRoute
  ContactUsRoute: typeof ContactUsRoute
  FaqsRoute: typeof FaqsRoute
  MissionVisionRoute: typeof MissionVisionRoute
  ProgramsEnvironmentsRoute: typeof ProgramsEnvironmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision': {
      id: '/mission-vision'
      path: '/mission-vision'
      fullPath: '/mission-vision'
      preLoaderRoute: typeof MissionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs-environments': {
      id: '/programs-environments'
      path: '/programs-environments'
      fullPath: '/programs-environments'
      preLoaderRoute: typeof ProgramsEnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdmissionsRoute: AdmissionsRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRoute,
  ContactUsRoute: ContactUsRoute,
  FaqsRoute: FaqsRoute,
  MissionVisionRoute: MissionVisionRoute,
  ProgramsEnvironmentsRoute: ProgramsEnvironmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
